<?php

namespace App\Lib\Streams\Tests;

use Mockery\Mock;
use Tests\TestCase;

/**
 * Class AdServiceTest
 *
 * @package App\Lib\Streams\Tests
 * @author  Carlos Granados <granados.carlos91@gmail.com>
 */
class StreamServiceTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


}
