<?php

namespace App\Lib\Ads\Tests;

use Tests\TestCase;
use App\Lib\Ads\AdsService;
use App\Lib\Ads\Contracts\AdsRepository;

/**
 * Class AdServiceTest
 *
 * @package App\Lib\Ads\Tests
 * @author  Carlos Granados <granados.carlos91@gmail.com>
 */
class AdServiceTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAdSuccessNoCache()
    {
        // Disable caching
        \Config::set('services.' . AdsService::class . '.cache', false);

        $repository = $this->getMockBuilder(AdsRepository::class)
                           ->setMethods(['fetch'])
                           ->getMock();

        $repository->expects($this->once())->method('fetch')->with();

        // Override instance in service container with mock object
        $this->app->singleton(AdsRepository::class, $repository);

        $service = $this->app->make(AdsService::class);

    }

    public function testAdSuccessWithCache()
    {

    }

    public function testAdFailureNoBail()
    {

    }

    public function testAdFailureAndBail()
    {

    }
}
